---
- hosts: nginx
  tasks:
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%nginx=(ALL:ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'